[application]

name = "Open Strength"

default_platform = "web"

out_dir = "dist"

[web.app]

# HTML title tag content
title = "Open Strength"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.watcher]

reload_html = true

watch_path = ["src", "assets"]
